# Generated by Django 5.1.3 on 2024-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="Name", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="Last_name", max_length=50),
            preserve_default=False,
        ),
    ]
