# Generated by Django 5.1.3 on 2024-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.jpg",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
