# Generated by Django 5.1.3 on 2024-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_alter_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="social.tag"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.CheckConstraint(
                condition=models.Q(("id__lte", 10)), name="max_10_images_per_post"
            ),
        ),
    ]
