# Generated by Django 5.1.3 on 2024-11-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_remove_image_description_remove_tag_posts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
    ]
