# Generated by Django 5.1.3 on 2024-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_remove_post_content"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="image",
            name="max_10_images_per_post",
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.jpg", upload_to="avatars/"
            ),
        ),
    ]
